# Generated by Django 2.0.1 on 2020-05-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leads',
        ),
    ]
